### ISSUE TITLE
Intégrate

### ISSUE THREAD

**Issue by thejonashub** [music-notation-swift/music-notation#2]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by woolie** [comment]
Not a real issue, closing.

**Comment by thejonashub** [comment]
How do I fix all the security issues I’m facing from licenses and other contributors ? Sent from my iPhone. El 11 dic 2024, a la(s) 10:25, Steven Woolgar ***@***.***> escribió:﻿
Is there an issue I can help with?

**Comment by thejonashub** [comment]
All my information is exposed in GitHub!

**Comment by woolie** [comment]
Not quite sure why you are adding issues to this repo. This is clearly unrelated.

**Comment by thejonashub** [comment]
You are working over my intellectual property ! Infringement and Security damages Sent from my iPhone. El 11 dic 2024, a la(s) 13:25, Steven Woolgar ***@***.***> escribió﻿
Not quite sure why you are adding issues to this repo. This is clearly unrelated.
